sudo: false
language: python
matrix:
  include:
    - python: '3.7'
      install:
      - pip install flake8
      - pip install mypy
      script:
      - flake8
      - cd python && mypy -p lsst.daf.butler
