datastore:
  cls: lsst.daf.butler.datastores.webdavDatastore.WebdavDatastore
  root: <butlerRoot>/datastore
  records:
    table: webdav_datastore_records
  create: true
  templates:
    # valid_first and valid_last here are YYYYMMDD; we assume we'll switch to
    # MJD (DM-15890) before we need more than day resolution, since that's all
    # Gen2 has.
    default: "{run:/}/{datasetType}.{component:?}/{tract:?}/{patch:?}/{label:?}/{band:?}/{subfilter:?}/{physical_filter:?}/{visit:?}/{datasetType}_{component:?}_{tract:?}_{patch:?}_{label:?}_{band:?}_{physical_filter:?}_{visit:?}_{exposure:?}_{detector:?}_{instrument:?}_{skymap:?}_{skypix:?}_{run}"
  formatters: !include formatters.yaml
  composites: !include composites.yaml
