name: build_and_test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    # runs-on: ubuntu-latest
    # Need >= 20.04 for modern sqlite. Can switch to latest when
    # github change
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install sqlite
        run: sudo apt-get install sqlite libyaml-dev

      - name: Install postgresql (server)
        run: sudo apt install postgresql

      # pip is pinned because of urllib pinning because of moto bug with
      # responses
      - name: Update pip/wheel infrastructure
        run: |
          python -m pip install --upgrade pip==20.2.4
          pip install wheel

      - name: Install postgresql Python packages
        run: pip install psycopg2 testing.postgresql

      - name: Install cryptography package for moto
        run: pip install cryptography

      - name: Install WebDAV packages for testing
        run: pip install cheroot wsgidav

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        run: pip install pytest pytest-flake8 pytest-xdist pytest-openfiles

      - name: Build and install
        run: pip install -v .

      - name: Run tests
        run: pytest -r a -v -n 3 --open-files

      - name: Install documenteer
        run: pip install 'documenteer[pipelines]>=0.6'

      - name: Build documentation
        working-directory: ./doc
        run: package-docs build
